<?php

use Illuminate\Support\Facades\Route;

/**
 * @OA\Post(
 *     path="/oauth/token",
 *     tags={"token"},
 *     summary="Obtain a new set of tokens (access token + refresh token) from the IDP during the oAuth2 login process.
 *              Only the access token is presented in the output. The refresh token is stored in the database.",
 *     operationId="getTokens",
 *     @OA\Parameter(
 *         name="code",
 *         in="query",
 *         description="Authorization code received from the IDP during the auth code flow.",
 *         required=true,
 *         @OA\Schema(
 *             type="string",
 *             example="def50200e355d83ddc11b968b703fd130993fb4195dc9f60309f4be069723f1de0fa68f477537c7dad9f9f466d531e582f54558e982818d29bfc107348c99f68e6bf43e9e0fe94925341a6bfd5c49e13adaf6708dbf0333e64b868fb85862a96e088fa1bc070c9df05bdde6d3e16e95d51498764097b0cde6db0b932e13de1a65fea33390e400ac815e61cc975ab7c1f595dae13ecf5925673104427c6cc17e071c751185318ebdc0d2efc7ae59adc8da6b68c67a1e6a8d990063f3cfa54360b9af5ad3348b89765e7fb549bfe098b615e266b1e0ab4497fe00f1957b43de1d4af19df63c4bb5a3a830c9b4f305ba38a31a4a32ac9644f8308aa2592e48754dfa784081bbb5084115c830676052d6b761fa7b25cb9e7b3531f41e68a0266a98c5731b88ffe421ece125879f155cea0e4f1d85c67654c175a7eb49b3482733c13a99cdd62325a89e730aaca8594dc619feedbbaa385fa207290c294f124e42d6708a4c7b80d887ca77b0e1cfcb9b025ebf91fe085faabd979"
 *         )
 *     ),
 *     @OA\Response(
 *         response=200,
 *         description="Success",
 *         @OA\JsonContent(ref="#/components/schemas/token"),
 *     ),
 *     @OA\Response(
 *         response=401,
 *         description="Unauthorized.",
 *         @OA\JsonContent(ref="#/components/schemas/error4xx"),
 *     ),
 *     @OA\Response(
 *         response=500,
 *         description="Internal server error",
 *         @OA\JsonContent(ref="#/components/schemas/error5xx"),
 *     ),
 * )
 */
Route::group(
    ['prefix' => 'api/v1', 'middleware' => [], 'namespace' => 'AB\OAuthTokenValidator\Http\Controllers'],
    function () {
        Route::post('/oauth/token', ['as' => 'api.oauth.access-token', 'uses' => 'OAuth2Controller@issueToken']);
    }
);

/**
 * @OA\Post(
 *     path="/oauth/refresh-token",
 *     tags={"token"},
 *     summary="Obtain a new set of tokens (access token + refresh token) from the IDP using the refresh token.",
 *     operationId="getTokensFromRefreshToken",
 *     @OA\Response(
 *         response=200,
 *         description="Success",
 *         @OA\JsonContent(ref="#/components/schemas/token"),
 *     ),
 *     @OA\Response(
 *         response=401,
 *         description="Unauthorized.",
 *         @OA\JsonContent(ref="#/components/schemas/error4xx"),
 *     ),
 *     @OA\Response(
 *         response=500,
 *         description="Internal server error",
 *         @OA\JsonContent(ref="#/components/schemas/error5xx"),
 *     ),
 *     security={
 *       {"Bearer Token": {""}}
 *     }
 * )
 */
Route::group(
    ['prefix' => 'api/v1', 'middleware' => ['validateToken'], 'namespace' => 'AB\OAuthTokenValidator\Http\Controllers'],
    function () {
        Route::post('/oauth/refresh-token', [
            'as' => 'api.oauth.refresh-token',
            'uses' => 'OAuth2Controller@refreshToken'
        ]);
    }
);

/**
 * @OA\Post(
 *     path="/oauth/logout",
 *     tags={"token"},
 *     summary="Logs the user out using the special logout token generated by the IDP.",
 *     operationId="logout",
 *     @OA\Parameter(
 *         name="logout_token",
 *         in="query",
 *         description="JWT logout token generated by the IDP.",
 *         required=true,
 *         @OA\Schema(
 *             type="string",
 *             example="eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IndWajlNR1Y0S01PZlNkblZPcUFHY0swZVhwbjZzV2VVZldqbVJxQXk3RFJ1U0RUbmJ0R0x3Rmd2VVo1S1IxR2dJdHAySmh4cTBPakV6dE5tIn0.eyJpc3MiOiJodHRwOlwvXC9iYmF1dGgubG9jYWwiLCJhdWQiOiJkMzEwOTJhOS1kMzljLTU1YzAtODcxNy1hZmE5NTM1N2Y1MDYiLCJqdGkiOiJ3Vmo5TUdWNEtNT2ZTZG5WT3FBR2NLMGVYcG42c1dlVWZXam1ScUF5N0RSdVNEVG5idEdMd0ZndlVaNUtSMUdnSXRwMkpoeHEwT2pFenRObSIsImlhdCI6MTU2MjA2MjUwMCwic3ViIjoiM2VmYWZhZDYtOTVkZS0zMWZlLWIzZjUtN2RhZmVjMGMzOGE1IiwiZXZlbnRzIjp7Imh0dHA6XC9cL3NjaGVtYXMub3BlbmlkLm5ldFwvZXZlbnRcL2JhY2tjaGFubmVsLWxvZ291dCI6e319fQ.nt-bNNn12whd7Xo48eb6EXRxEJG8Jgo_TAWhkAxkxVyk--HjBUVHeGUZEo4HwoDpc-OLRCqEoBIm_Qo60mYau2NpxPDmCQSP7pUzADfpk8ysryF81yO0anTWFMNBZoIWUGZlKH5wwXx3ziZZCItlg_T8sdt8CD_7TPiGVVgDEwUWFvyUgzObzvJQww7fO8fgyfsbr62H0nhaLz_E5Sx_SJxVty84LmOB6W1G-s0A0Z12ZObohJdckrUtIgHrhetKKPXF38ylsx9JRvdT2QS1RBadOcDyOX_Mg2y7-xjL10PIrln_prjVkhp6oaNwZqDOIwF_5K5b09ZjsSpvTXnXeTHooo1FHMQHwKSXK-GqkG_STt1pfLAS9Z9tyqFfdLyz2Au-0xIur8z-jlXuXzcWziU2f9BXfDeoc4-W2kf7dXjafLg0DM61Vf_e3qJYvfR1N8UAOaFdK0T1txENewcpCWm8RwubBfemh2cvOI_fqImYwkRkpH6ITYLYuMskQPC01s-H2RgUxhZWmgtd-JamzYnWr491y3HKMRs6JlFYWq0MRbLmTM7MVTzqDDSWpV1xMTC9GJhAn9kCPPXoaKapDenl6jLhQPHa4i_UDBb4OYw7l4x2evdMgJzROZ4_5HH55KwZzUys7KwP-dfCS5OOgRjHhFBDU0SlWbNFJCqzvko"
 *         )
 *     ),
 *     @OA\Response(
 *         response=200,
 *         description="Success",
 *         @OA\JsonContent(ref="#/components/schemas/token"),
 *     ),
 *     @OA\Response(
 *         response=401,
 *         description="Unauthorized.",
 *         @OA\JsonContent(ref="#/components/schemas/error4xx"),
 *     ),
 *     @OA\Response(
 *         response=500,
 *         description="Internal server error",
 *         @OA\JsonContent(ref="#/components/schemas/error5xx"),
 *     ),
 * )
 */
Route::group(
    [
        'prefix' => 'api/v1',
        'middleware' => ['validateLogoutToken'],
        'namespace' => 'AB\OAuthTokenValidator\Http\Controllers'
    ],
    function () {
        Route::post('/oauth/logout', ['as' => 'api.oauth.logout', 'uses' => 'OAuth2Controller@logout']);
    }
);
